# Generated by Django 4.2.2 on 2023-06-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_dough_cheese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dough',
            name='pizza',
        ),
        migrations.DeleteModel(
            name='Cheese',
        ),
        migrations.DeleteModel(
            name='Dough',
        ),
    ]
