# Generated by Django 4.2.2 on 2023-06-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_pizza_date_added_topping_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='pizza',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
