# Generated by Django 4.2.2 on 2023-06-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
