# Generated by Django 4.2.2 on 2023-06-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_alter_topping_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topping',
            new_name='Entry',
        ),
    ]
